version: '3'
services:
  buildchain:
    build:
      context: .
      dockerfile: ./docker-config/buildchain/Dockerfile
    volumes:
      - node-modules:/project/node_modules
      - ./docker-config/buildchain/package.json:/project/package.json
      - ./src:/project/src

  nginx:
    build:
      context: .
      dockerfile: ./docker-config/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - cpresources:/var/www/html/web/cpresources
      - ./src/web:/var/www/html/web

  php:
    build:
      context: .
      dockerfile: ./docker-config/php/Dockerfile
    expose:
      - 9000
    volumes:
      - cpresources:/app/web/cpresources
      - ./src/composer.json:/app/composer.json
      - ./src/composer.lock:/app/composer.lock
      - ./src/config:/app/config
      - ./src/modules:/app/modules
      - ./src/templates:/app/templates
      - ./src/web:/app/web
    environment:
      CRAFT_ENVIRONMENT: dev
      CRAFT_DB_DRIVER: mysql
      CRAFT_DB_SERVER: database
      CRAFT_DB_USER: project
      CRAFT_DB_PASSWORD: project
      CRAFT_DB_DATABASE: project
      CRAFT_DB_SCHEMA: public
      CRAFT_DB_TABLE_PREFIX: craft_
      CRAFT_SITE_URL: http://localhost
      CRAFT_SECURITY_KEY: AAAAAAAAAAAAAAAAAAAAAAAAAAA

  database:
      image: mariadb:10.3
      volumes:
        - db-data:/var/lib/mysql
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: project
        MYSQL_USER: project
        MYSQL_PASSWORD: project

volumes:
  db-data:
  cpresources:
  node-modules: